apiVersion: v1
kind: Pod
metadata:
  name: shpod
  labels:
    app: shpod
spec:
  volumes:
  - name: home
    persistentVolumeClaim:
      claimName: shpod
  - name: pubkey
    configMap:
      name: shpod
  containers:
  - name: sshd
    image: alpine
    volumeMounts:
    - name: home
      mountPath: /home
    - name: pubkey
      mountPath: /home/user/.ssh
    command:
    - sh
    - -c
    - |
      set -e
      apk add openssh
      ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
      echo "StrictModes no" >> /etc/ssh/sshd_config
      echo "group:x:1000:" >> /etc/group
      echo "user:x:1000:1000::/home/user:/bin/sh" >> /etc/passwd
      mkdir -p /home/user
      chown user /home/user
      exec /usr/sbin/sshd -D -e
