apiVersion: v1
kind: PersistentVolume
metadata:
  name: shpod
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/shpod"