apiVersion: v1
kind: Service
metadata:
  name: shpod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: shpod
  type: LoadBalancer 