apiVersion: v1
kind: Service
metadata:
  name: shpod
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: shpod
  type: LoadBalancer
#  loadBalancerIP: 192.168.178.211
